site_name: The Lexicon Project

nav:
 - Summary:
   - docs/index.md
 - Symbols:
   - Colors:
     - docs/symbols/colors/Colors.md
     - Bl█ck: docs/symbols/colors/Bl█ck.md
     - Blue: docs/symbols/colors/Blue.md
     - Gr██n: docs/symbols/colors/Gr██n.md
     - Or█nge: docs/symbols/colors/Or█nge.md
     - P█rple: docs/symbols/colors/P█rple.md
     - R█d: docs/symbols/colors/R█d.md
     - Wh█te: docs/symbols/colors/Wh█te.md
     - Yell█w: docs/symbols/colors/Y█llow.md
   - Counter-Divine Will:
      docs/symbols/CounterDivine_Will/index.md
   - Elements: docs/symbols/elements/Elements.md
     - Earth: docs/symbols/elements/Earth.md
     - Air: docs/symbols/elements/Air.md
     - F█re: docs/symbols/elements/F█re.md
     - Wat█r: docs/symbols/elements/Wat█r.md
     - Spir█t: docs/symbols/elements/Spir█t.md
     - Met█l: docs/symbols/elements/Met█l.md
       
theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        
    icon:
      admonition:
      info: material/cloud-alert

    features:
      - navigation.instant
      - navigation.expand
      - navigation.indexes
      - navigation.top
      - navigation.sections

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true
      toc_depth: 0

plugins:
  - search
  - roamlinks 
  - mermaid2
  
extra:
  generator: false


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
