site_name: The Lexicon Project
site_url: https://github.com/tindalos/Lexicon/docs

# repo_url: https://github.com/Tindalos/Lexicon
# repo_name: Lexicon
# edit_uri: docs/

       
theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        
    icon:
      admonition:
      info: material/cloud-alert

    features:
      - navigation.instant
#      ^ Loads the whole site at once, preventing constant reloads
      - navigation.indexes
#     ^ Displays index pages for section directories, allegedly  
      - navigation.top
#      ^ Creates a 'Back-to-top' button
#      - navigation.sections

nav:
#    - Home: index.md
#    - Section: 
#        - Section/index.md
#        - Page 1: Section/page1.md
#        - Page 2: Section/page2.md
    - Summary: index.md
    - Frequent Answers:
        - FrequentAnswers/index.md
    - Symbols:
        - symbols/index.md
        - Counter-Divine Will:
            - symbols/cdw/index.md
    - Elements:
        - /symbols/elements/index.md
        - Earth: /symbols/elements/earth.md
        - Air:  /symbols/elements/air.md
        - F█re: /symbols/elements/f█re.md
        - Wat█r: /symbols/elements/wat█r.md
        - Spir█t: /symbols/elements/spir█t.md
        - Met█l: /symbols/elements/met█l.md


# Extensions
markdown_extensions:
  - admonition
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true
      toc_depth: 0

plugins:
  - search
  - roamlinks 
  - mermaid2

extra:
  generator: false


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
