site_name: The Lexicon Project
site_url: https://github.com/tindalos/Lexicon/docs

# repo_url: https://github.com/Tindalos/Lexicon
# repo_name: Lexicon
# edit_uri: docs/

       
theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        
    icon:
      admonition:
      info: material/cloud-alert

    features:
      - navigation.instant
#      ^ Loads the whole site at once, preventing constant reloads
      - navigation.indexes
#     ^ Displays index pages for section directories, allegedly  
      - navigation.top
#      ^ Creates a 'Back-to-top' button
#      - navigation.sections

nav:
#    - Home: index.md
#    - Section: 
#        - Section/index.md
#        - Page 1: Section/page1.md
#        - Page 2: Section/page2.md
    - Summary: index.md
    - 'Frequent Answers':
        - FrequentAnswers/index.md
        - Why I redact: FrequentAnswers/Redaction.md
        - Who these guys are: FrequentAnswers/TheseGuys.md
        - How symbolism works: FrequentAnswers/Symbolism.md
    - Symbols:
        - Symbols/index.md
        - 'Counter-Divine Will':
            - Symbols/cdw/index.md
        - Elements:
            - Symbols/Elements/index.md
            - Earth: Symbols/Elements/Earth.md
            - Air:  Symbols/Elements/Air.md
            - F█re: Symbols/Elements/F█re.md
            - Wat█r: Symbols/Elements/Wat█r.md
            - Spir█t: Symbols/Elements/Spir█t.md
            - Met█l: Symbols/Elements/Met█l.md
        - Idols:
            - Symbols/Idols/index.md
            - Isht█r: Symbols/Idols/Isht█r.md
            - Ze█s: Symbols/Idols/Ze█s.md
            - Fid█s: Symbols/Idols/Fid█s.md
            - P█n]:' Symbols/Idols/P█n.md
            - B██l: Symbols/Idols/B██l.md
            - Ar█s: Symbols/Idols/Ar█s.md
            - Mol█ch: Symbols/Idols/Mol█ch.md
        - Col█rs:
            - Symbols/Col█rs/index.md
            - Bl█ck: Symbols/Col█rs/Bl█ck.md
            - Blue: Symbols/Col█rs/Blue.md
            - Br█wn: Symbols/Col█rs/Br█wn.md
            - Or█nge: Symbols/Col█rs/Or█nge.md
            - P█rple: Symbols/Col█rs/P█rple.md
            - R█d: Symbols/Col█rs/R█d.md
            - Wh█te: Symbols/Col█rs/Wh█te.md
            - Yell█w: Symbols/Col█rs/Yell█w.md
        - 'Modes':
            - Symbols/Modes/index.md
    - Tropes:
        - Tropes/index.md
        - No Anti-: Tropes/NoAnti.md

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true
      toc_depth: 0

plugins:
  - search
  - roamlinks 
  - mermaid2

extra:
  generator: false


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
