site_name: The Lexicon Project
site_url: https://github.com/tindalos/Lexicon/docs
site_description: Lexicon of Babylonian Kabbalist organizing symbolism

# repo_url: https://github.com/Tindalos/Lexicon
# repo_name: Lexicon
# edit_uri: docs/

       
theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        
    icon:
      admonition:
        info: material/cloud-alert
#    favicon: img/book.png
#    logo: img/book.png

    features:
      - navigation.instant
#      ^ Loads the whole site at once, preventing constant reloads
      - navigation.indexes
#     ^ Displays index pages for section directories  
      - navigation.top
#      ^ Creates a 'Back-to-top' button
#      - navigation.sections

nav:
    - Summary: index.md
    - 'Frequent Answers':
        - FrequentAnswers/index.md
        - Why I redact: FrequentAnswers/Redaction.md
        - Who these guys are: FrequentAnswers/TheseGuys.md
        - How symbolism works: FrequentAnswers/Symbolism.md
        - How 'layering' works: FrequentAnswers/Layering.md
        - About the Telepaths and Propheciers: FrequentAnswers/TelepathsPropheciers.md
        - Lexicon syntax: FrequentAnswers/Syntax.md
        - How this was made: FrequentAnswers/HowMade.md
    - Symbols:
        - Symbols/index.md
        - 'Counter-Divine Will':
            - Symbols/cdw/index.md
            - W█sh: Symbols/cdw/W█sh.md
            - Fec█s: Symbols/cdw/Fec█s.md
            - Corporation: Symbols/cdw/Corporation.md
            - Vir█s: Symbols/cdw/Vir█s.md
            - Pal█ndrome: Symbols/cdw/Pal█ndrome.md
            - Pen█tration: Symbols/cdw/Pen█tration.md
            - Ins█cts: Symbols/cdw/Ins█cts.md
            - C█ts: Symbols/cdw/C█ts.md
        - Basics:
            - Symbols/Basics/index.md
            - F██d: Symbols/Basics/F██d.md
            - Dr█nk: Symbols/Basics/Dr█nk.md
            - Bl█de: Symbols/Basics/Bl█de.md
            - Gem█ni: Symbols/Basics/Gem█ni.md
            - D█ll: Symbols/Basics/D█ll.md
            - M█sk: Symbols/Basics/M█sk.md
            - Perf█rmance: Symbols/Basics/Perf█rmance.md
            - Ch█kras: Symbols/Basics/Ch█kras.md
            - L█ve: Symbols/Basics/L█ve.md
            - D█rkness: Symbols/Basics/D█rkness.md
            - Dre█m: Symbols/Basics/Dre█m.md
            - In Container: Symbols/Basics/InContainer.md
            - Ch█nge: Symbols/Basics/Ch█nge.md
            - Myst█ry: Symbols/Basics/Myst█ry.md
            - Life: Symbols/Basics/Life.md
            - De█th: Symbols/Basics/De█th.md
            - Mag█ck: Symbols/Basics/Mag█ck.md
            - Beli█f: Symbols/Basics/Beli█f.md
            - Sm█le: Symbols/Basics/Sm█le.md
            - Democracy: Symbols/Basics/Democracy.md
            - Labyr█nth: Symbols/Basics/Labyr█nth.md
            - Obel█sk: Symbols/Basics/Obel█sk.md
            - T█chnology: Symbols/Basics/T█chnology.md
            - J█mp: Symbols/Basics/J█mp.md
            - Po█nt: Symbols/Basics/Po█nt.md
            - M█rriage: Symbols/Basics/M█rriage.md
            - St█p On: Symbols/Basics/St█pOn.md
            - Dece█t: Symbols/Basics/Dece█t.md
            - Voice: Symbols/Basics/Voice.md
            - Expl█sion: Symbols/Basics/Expl█sion.md
            - W█r: Symbols/Basics/W█r.md
            - Br█dge: Symbols/Basics/Br█dge.md
            - In fr█nt of: Symbols/Basics/InFr█ntOf.md
            - H█nd: Symbols/Basics/H█nd.md
            - Sacrif█ce: Symbols/Basics/Sacrif█ce.md
        - Elements:
            - Symbols/Elements/index.md
            - Earth: Symbols/Elements/Earth.md
            - Air:  Symbols/Elements/Air.md
            - F█re: Symbols/Elements/F█re.md
            - Wat█r: Symbols/Elements/Wat█r.md
            - Spir█t: Symbols/Elements/Spir█t.md
            - Met█l: Symbols/Elements/Met█l.md
            - D█st: Symbols/Elements/D█st.md
            - Gl█ss: Symbols/Elements/Gl█ss.md
            - M█d: Symbols/Elements/M█d.md
            - Br█ck: Symbols/Elements/Br█ck.md
            - Oobl█ck: Symbols/Elements/Oobl█ck.md
        - Idols:
            - Symbols/Idols/index.md
            - Isht█r: Symbols/Idols/Isht█r.md
            - Ze█s: Symbols/Idols/Ze█s.md
            - Tiam█t: Symbols/Idols/Tiam█t.md
            - Fid█s: Symbols/Idols/Fid█s.md
            - P█n: Symbols/Idols/P█n.md
            - B██l: Symbols/Idols/B██l.md
            - Ar█s: Symbols/Idols/Ar█s.md
            - Mol█ch: Symbols/Idols/Mol█ch.md
            - Dag█n: Symbols/Idols/Dag█n.md
            - Osir█s: Symbols/Idols/Osir█s.md
            - Is█s: Symbols/Idols/Is█s.md
            - Hor█s: Symbols/Idols/Hor█s.md
            - Aphrod█te: Symbols/Idols/Aphrod█te.md
            - Remph█n: Symbols/Idols/Remph█n.md
            - F█tes: Symbols/Idols/F█tes.md
            - H█ra: Symbols/Idols/H█ra.md
            - J█no: Symbols/Idols/J█no.md
            - J█nus: Symbols/Idols/J█nus.md
            - Lib█rtas: Symbols/Idols/Lib█rtas.md
            - Nem█sis: Symbols/Idols/Nem█sis.md
            - Atl█s: Symbols/Idols/Atl█s.md
            - Ap█s: Symbols/Idols/Ap█s.md
            - F█rtuna: Symbols/Idols/F█rtuna.md
        - Efforts In-Process:
            - Symbols/In-Process/index.md
            - Col█rs:
                - Symbols/In-Process/Col█rs/index.md
                - Bl█ck: Symbols/In-Process/Col█rs/Bl█ck.md
                - Blue: Symbols/In-Process/Col█rs/Blue.md
                - Br█wn: Symbols/In-Process/Col█rs/Br█wn.md
                - Or█nge: Symbols/In-Process/Col█rs/Or█nge.md
                - P█rple: Symbols/In-Process/Col█rs/P█rple.md
                - R█d: Symbols/In-Process/Col█rs/R█d.md
                - Wh█te: Symbols/In-Process/Col█rs/Wh█te.md
                - Yell█w: Symbols/In-Process/Col█rs/Yell█w.md
                - Gr██n: Symbols/In-Process/Col█rs/Gr██n.md
            - Trav█l: Symbols/In-Process/Trav█l.md
            - Rot█tion: Symbols/In-Process/Rot█tion.md
            - F██l: Symbols/In-Process/F██l.md
            - G█me: Symbols/In-Process/G█me.md
            - Em█tion: Symbols/In-Process/Em█tion.md
        - Numbers:
            - Symbols/Numbers/index.md
            - Z█ro: Symbols/Numbers/Z█ro.md
            - One: Symbols/Numbers/One.md
            - Tw█: Symbols/Numbers/Tw█.md
            - Thr██: Symbols/Numbers/Thr██.md
            - Fo█r: Symbols/Numbers/Fo█r.md
            - F█ve: Symbols/Numbers/F█ve.md
            - S█x: Symbols/Numbers/S█x.md
            - Seven: Symbols/Numbers/Seven.md
            - E█ght: Symbols/Numbers/E█ght.md
            - N█ne: Symbols/Numbers/N█ne.md
            - T█n: Symbols/Numbers/T█n.md
            - El█ven: Symbols/Numbers/El█ven.md
            - Tw█nty-Tw█: Symbols/Numbers/Tw█nty-Tw█.md
            - Inf█nity: Symbols/Numbers/Inf█nity.md
        - Visual:
            - Symbols/Visual/index.md
            - W█vy L█nes: Symbols/Visual/W█vyL█ne.md
            - Stra█ght L█nes: Symbols/Visual/Stra█ghtL█ne.md
            - Jagged L█nes: Symbols/Visual/JaggedL█ne.md
            - Spir█l: Symbols/Visual/Spir█l.md
            - B██l-Had█d: Symbols/Visual/B██l-Had█d.md
            - Diag█nalL█ne: Symbols/Visual/Diag█nalL█ne.md
            - Do█bleTr█angle: Symbols/Visual/Do█bleTr█angle.md
            - Spir█l: Symbols/Visual/Spir█l.md
        - 'Modes':
            - Symbols/Modes/index.md
            - Cha█s:
                - Symbols/Modes/Cha█s/index.md
            - Inversion:
                - Symbols/Modes/Inversion/index.md
                - Drag█n: Symbols/Modes/Inversion/Drag█n.md
                - Espi█nage: Symbols/Modes/Inversion/Espi█nage.md
                - Sp█ce: Symbols/Modes/Inversion/Sp█ce.md
        - Seldom Use:
            - Symbols/SeldomUse/index.md
            - R█se: Symbols/SeldomUse/R█se.md
            - Phoen█x: Symbols/SeldomUse/Phoen█x.md
            - Dec█pitation: Symbols/SeldomUse/Dec█pitation.md
    - Tropes:
        - Tropes/index.md
        - 'No Anti-': Tropes/NoAnti.md
        - Geometry as Numbers: Tropes/GeometryAsNumbers.md
        - F█ther, M█ther, Child: Tropes/F█therM█therChild.md
        - 'Multiple In-Process Symbols': Tropes/MultipleInProcess.md
        - Arbitrary Vowels: Tropes/ArbitraryVowels.md
    - Examples:
      - Examples/index.md
# Extensions
markdown_extensions:
#  - abbr
  - admonition
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
#  - pymdownx.snippets
  - pymdownx.tilde

  - toc:
      permalink: true
      toc_depth: 0

plugins:
  - search
  - roamlinks 
  - mermaid2
  - rss

extra:
  generator: false


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
#test
